---
- name: Minecraft Server Setup
  hosts: all
  become: true
  become_user: root
  roles:
    - {
      role: nolte.msopenjdk,
      jdk_used_version: '17'
    }
    - {
      role: nolte.minecraft,
      minecraft_eula_accept: true
    }
