---
- name: Minecraft Server Setup
  hosts: all
  become: true
  become_user: root
  vars_files:
    - settings.yml
  pre_tasks:
    - name: Setup remote machine (gather informations)
      setup:
      register: setup_status
      until: setup_status is success
      delay: 10
      retries: 3
